// Code generated by go-swagger; DO NOT EDIT.

package todos

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"learn/models"
)

// GetAllOKCode is the HTTP code returned for type GetAllOK
const GetAllOKCode int = 200

/*
GetAllOK list the todo operations

swagger:response getAllOK
*/
type GetAllOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Item `json:"body,omitempty"`
}

// NewGetAllOK creates GetAllOK with default headers values
func NewGetAllOK() *GetAllOK {

	return &GetAllOK{}
}

// WithPayload adds the payload to the get all o k response
func (o *GetAllOK) WithPayload(payload []*models.Item) *GetAllOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all o k response
func (o *GetAllOK) SetPayload(payload []*models.Item) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Item, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetAllDefault generic error response

swagger:response getAllDefault
*/
type GetAllDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAllDefault creates GetAllDefault with default headers values
func NewGetAllDefault(code int) *GetAllDefault {
	if code <= 0 {
		code = 500
	}

	return &GetAllDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get all default response
func (o *GetAllDefault) WithStatusCode(code int) *GetAllDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get all default response
func (o *GetAllDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get all default response
func (o *GetAllDefault) WithPayload(payload *models.Error) *GetAllDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get all default response
func (o *GetAllDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAllDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
