-- This tutorial is about aggregate functions such as COUNT, SUM and AVG. An aggregate function takes many values and delivers just one value. For example the function SUM would aggregate values 2,4 and 5 to deliver the single value 11.
-- Aggregates: the functions SUM
