.PHONY: TestLeetCode
TestLeetCode:
	go test -v -count=1 -run ${name} algorithm/leetcode

.PHONY: BenchLeetCode
BenchLeetCode:


.PHONY: TestVNoi
TestVNoi:
	go test -v -count=1 -run ${name} algorithm/vnoi


# sed
# sed -i 's|package main|package leetcode|g' ./*.go   
