openapi: "3.0.0"
info:
  version: 1.0.0
  title: trainings
  description: TODO
servers:
  - url: https://{{hostname}}/api
    variable:
      hostname:
        default: localhost
security:
  - bearerAuth: []
path:
  /trainings:
    get:
      operationId: getTrainings
      reponses:
        "200":
          description: todo
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trainings"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
