CREATE TABLE
  users (
    `id` int (11) NOT NULL AUTO_INCREMENT, -- UNSIGNED
    `username` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `password` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
    `fullname` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `tel` varchar(50) CHARSET ascii DEFAULT NULL,
    `tel2` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `validate_tel` tinyint (2) DEFAULT '0',
    `birthday` datetime DEFAULT NULL, -- date
    `remember_password` tinyint (1) DEFAULT '0',
    `email` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL, -- check email COLLATE
    `ecom_password` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `img` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `group_id` int (11) NOT NULL, -- SMALLINT - MEDIUMINT: SELECT COUNT(*) FROM groups (185)
    `acl_group_id` int (11) DEFAULT NULL, -- SMALLINT - MEDIUMINT
    `status_id` int (11) NOT NULL DEFAULT '1' COMMENT '1: inactive, 2: locked, 3: actived', -- TINYINT
    `station_id` int (10) unsigned DEFAULT NULL,
    `module_id` varchar(50) CHARACTERSET ascii DEFAULT NULL,
    `virtual_user` tinyint (2) DEFAULT '0' COMMENT 'Tài khoản ảo',
    `manage_all_stations` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `manage_all_packages` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `manage_all_shops` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `manage_all_cods` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `manage_all_carts` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `manage_all_ticket` tinyint (4) DEFAULT '0',
    `is_group_manager` tinyint (4) NOT NULL DEFAULT '0',
    `last_changed_pw` datetime DEFAULT NULL,
    `created` datetime DEFAULT CURRENT_TIMESTAMP,
    `created_by` int (11) DEFAULT NULL, -- unsigned int
    `modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `modified_by` int (11) DEFAULT NULL, -- unsigned int
    `manager_sale_edit` tinyint (4) NOT NULL,
    `link_avatar` varchar(1000) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Link avatar c?a COD',
    `master_profile_id` int (11) NOT NULL DEFAULT '0' COMMENT 'id của master_profiles',
    `iam_id` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `external` tinyint (4) DEFAULT '0',
    `company_id` int (11) DEFAULT NULL,
  );

CREATE TABLE
  `packages` (
    `id` char(36) COLLATE utf8_unicode_ci NOT NULL,
    `shop_id` char(36) COLLATE utf8_unicode_ci NOT NULL,
    `shop_code` varchar(100) CHARSET utf8 DEFAULT NULL COMMENT 'denormalized. Only for searching',
    `client_id` varchar(250) CHARSET utf8 DEFAULT NULL,
    `client_id_display` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_f` tinyint (1) DEFAULT '0' COMMENT '0. COD th??ng l?y, 1. COD F l?y',
    `deliver_f` tinyint (1) DEFAULT '0' COMMENT '0. COD th??ng giao, 1. COD F giao',
    `spt` tinyint (1) DEFAULT '0' COMMENT '0. hi?n th? c? hai team th?y, 1. ch? cho 1 team th?y',
    `opm` tinyint (1) DEFAULT '0' COMMENT '0. ??n th??ng, 1. ??n ch? thu ti?n',
    `sdt` tinyint (1) DEFAULT '0' COMMENT '0. hi?n th? c? hai team th?y, 1. ch? cho 1 team th?y',
    `client_package_no` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `client_is_cancel` tinyint (3) unsigned DEFAULT '0',
    `courier_id` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
    `red_bill_code` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
    `order` bigint (20) NOT NULL AUTO_INCREMENT,
    `alias` varchar(50) CHARSET utf8 DEFAULT 'N/D',
    `oa` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'original alias',
    `package_status_id` int (10) unsigned NOT NULL DEFAULT '1',
    `is_express` tinyint (3) unsigned DEFAULT '0' COMMENT '1: express, 0: not',
    `is_freeship` tinyint (3) unsigned DEFAULT '0' COMMENT '1: free ship, 0: not',
    `is_cancel` tinyint (3) unsigned DEFAULT '0' COMMENT '1: is canceled, 0: not',
    `is_exported` tinyint (3) unsigned NOT NULL DEFAULT '0' COMMENT '1: is exported, 0: not yet',
    `is_refunded` tinyint (3) unsigned DEFAULT '0' COMMENT '1: is refund, 0: not yet',
    `is_evicted` tinyint (3) unsigned DEFAULT '0' COMMENT '1: is evicted, 0: not yet',
    `is_distributed` tinyint (3) unsigned DEFAULT '0' COMMENT '1: is distributed, 0: not',
    `area_relative` tinyint (3) unsigned DEFAULT NULL COMMENT '1: is inner Hanoi''s city, 2: outer Hanoi''s city but is in Hanoi, 3: outer Hanoi',
    `return_status` tinyint (4) DEFAULT NULL COMMENT '0: not yet, 1: is returning, 2: returned, 3: not confirmed',
    `courier_status` tinyint (4) DEFAULT NULL COMMENT 'For tracking courier''s deliverer such as: PDA. 1: deliver successfully, 2: deliver failed, 3: success audited, 4: failure audit',
    `transfer_status` tinyint (3) unsigned DEFAULT '0' COMMENT '0: transfering, 1: not accepted, 2: accepted',
    `is_valid` tinyint (3) unsigned DEFAULT '1' COMMENT '1: is valid, 0: not valid',
    `need_confirm` tinyint (4) DEFAULT '0' COMMENT '1: need to confirm, 0: needn''t to confirm',
    `customer_code` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'customer''s code from client',
    `customer_fullname` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `customer_province_id` int (10) unsigned DEFAULT NULL,
    `customer_province` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'for storaging from client via api',
    `customer_district_id` int (10) unsigned DEFAULT NULL,
    `customer_district` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'for storaging from client via api',
    `customer_ward_id` int (10) unsigned DEFAULT NULL,
    `customer_ward` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'for storaging from client via api',
    `customer_street_id` int (10) unsigned DEFAULT NULL,
    `customer_street` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'for storaging from client via api',
    `customer_first_address` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `customer_last_address` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'denormalized',
    `customer_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `customer_tel` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `customer_tel_2` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `customer_lat` varchar(100) CHARSET utf8 DEFAULT NULL,
    `customer_lng` varchar(100) CHARSET utf8 DEFAULT NULL,
    `pick_address_id` int (10) unsigned DEFAULT NULL,
    `pick_fullname` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_province_id` int (11) DEFAULT NULL,
    `pick_province` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_district_id` int (11) DEFAULT NULL,
    `pick_district` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_ward_id` int (11) DEFAULT NULL,
    `pick_ward` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_street_id` int (11) DEFAULT NULL,
    `pick_street` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_first_address` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_last_address` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_tel` varchar(150) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_email` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_lat` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_lng` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
    `pick_address_id_hashed` varchar(250) COLLATE utf8_unicode_ci DEFAULT NULL,
    `package_type` tinyint (4) NOT NULL DEFAULT '1' COMMENT '1: is package, 2: is request',
    `package_type_id` tinyint (3) unsigned DEFAULT NULL,
    `express_type` tinyint (4) DEFAULT NULL COMMENT '1: standard, 2: instant, 3: express',
    `ship_money` int (10) unsigned DEFAULT '0',
    `pick_money` int (10) unsigned DEFAULT '0',
    `courier_money` int (10) unsigned DEFAULT NULL COMMENT 'Ship fee for courier',
    `is_pick_money` tinyint (3) unsigned DEFAULT '0' COMMENT '1: pick money, 0: not',
    `pick_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT '',
    `pick_cart_id` char(36) COLLATE utf8_unicode_ci DEFAULT '',
    `pick_work_shift` tinyint (4) DEFAULT NULL,
    `deliver_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT '',
    `deliver_cart_id` char(36) COLLATE utf8_unicode_ci DEFAULT '',
    `deliver_work_shift` tinyint (4) DEFAULT NULL,
    `return_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT '',
    `source` tinyint (3) unsigned DEFAULT '0' COMMENT '0: from webform, 1: from api, 2: from client form, 3: from excel file, 4: from magentoo, 5: from mobile app',
    `desc` text COLLATE utf8_unicode_ci,
    `message` text CHARSET utf8 COMMENT 'Public message',
    `private_message` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Private message',
    `token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Token of client for accessing the api',
    `approved_at` datetime DEFAULT NULL COMMENT 'The last time when the package is approved',
    `picked_at` datetime DEFAULT NULL COMMENT 'The time when the cod picks the package from customer',
    `delivered_at` datetime DEFAULT NULL COMMENT 'The time when the cod delivers the package to the destination',
    `transferred_at` datetime DEFAULT NULL COMMENT 'When source station exports the excel and confirm about transfering the packages',
    `accept_transfer_at` datetime DEFAULT NULL COMMENT 'The time when the package is accepted (transfer_status = 1) by destination station',
    `is_geocoded` tinyint (3) unsigned DEFAULT '0' COMMENT '1: is geocoded, 0: not yet',
    `verified_customer_address` tinyint (3) unsigned DEFAULT '0' COMMENT '1: verified, 0: not yet',
    `verified_pick_address` tinyint (3) unsigned DEFAULT '0' COMMENT '1: verified, 0: not yet',
    `pick_cod_fee` int (10) unsigned DEFAULT '0',
    `deliver_cod_fee` int (10) unsigned DEFAULT '0',
    `last_send_status_id` tinyint (4) DEFAULT NULL COMMENT 'Last send id to client',
    `took_at` datetime DEFAULT NULL COMMENT 'The time when the package is evicted by operator',
    `done_at` datetime DEFAULT NULL COMMENT 'The time when the cod returns money to the accountant or the courier notices that the package is done',
    `canceled_at` datetime DEFAULT NULL COMMENT 'The time when the package is canceled by admin or customer',
    `distributed_picking_at` datetime DEFAULT NULL COMMENT 'when status is 12',
    `distributed_delivering_at` datetime DEFAULT NULL COMMENT 'when status is 4',
    `distributed_returning_at` datetime DEFAULT NULL,
    `audited_at` datetime DEFAULT NULL COMMENT 'Time when the audited email is sent',
    `phone_confirmed_at` datetime DEFAULT NULL,
    `used_coupon` tinyint (3) unsigned DEFAULT NULL,
    `rt_delay` int (10) unsigned DEFAULT '0' COMMENT 's? ngày gi? l?i kho giao hàng ti?t ki?t tr??c khi ??i soát t? ??ng và tr? hàng',
    `destination_type` tinyint (4) DEFAULT NULL COMMENT 'options are in admin_configs.php',
    `package_bulk` int (11) DEFAULT NULL COMMENT 'A number for bulk package',
    `created_user_id` char(36) CHARSET utf8 DEFAULT '0',
    `created_username` varchar(255) COLLATE utf8_unicode_ci DEFAULT '0' COMMENT 'denormalized',
    `print_pick_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Print the picked up packages for COD',
    `print_deliver_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Print the delivered package for COD',
    `print_return_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Print the returned package',
    `is_printed_label` tinyint (2) DEFAULT '0' COMMENT 'Is printed the label or not',
    `sent_sms_pick_cod_id` char(36) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Sent the message to pick package to COD',
    `return_part_package` tinyint (4) DEFAULT '0' COMMENT 'Return a part of Package for shop when the package is not completely done',
    `down_fee_type` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Type to downgrade fee',
    `station_id` int (10) unsigned DEFAULT NULL,
    `current_station_id` int (11) DEFAULT NULL COMMENT 'kho ?ang có hàng c?a ??n',
    `transfer_station_id` int (10) unsigned DEFAULT NULL COMMENT 'Next station to transfer the package',
    `distance_from_station` int (10) unsigned DEFAULT '0',
    `distance_from_pick_address` int (10) unsigned DEFAULT '0',
    `modified_user_id` char(36) CHARSET utf8 DEFAULT '0',
    `modified_username` varchar(255) COLLATE utf8_unicode_ci DEFAULT '0' COMMENT 'denormalized',
    `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `modified` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `tmp_picking_status` tinyint (3) unsigned NOT NULL DEFAULT '0' COMMENT '0: default, 1: picked by cod, 2 not picked by cod, 3 delayed by cod, 4 picked by operator, 5 not picked by operator, 6 delayed by operator',
    `delay_pick_reason_code` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `period_to_delay_pick` varchar(50) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `date_to_delay_pick` datetime DEFAULT NULL,
    `not_picked_reason_code` varchar(100) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',
    `nth_picked` tinyint (4) unsigned NOT NULL DEFAULT '0',
    `pick_message` text COLLATE utf8_unicode_ci,
    `returning_at` datetime DEFAULT NULL,
    `returned_at` datetime DEFAULT NULL,
    `tmp_delivering_status` tinyint (3) unsigned NOT NULL DEFAULT '0' COMMENT '0: default',
    `deliver_message` text COLLATE utf8_unicode_ci,
    `nth_delivered` tinyint (4) unsigned DEFAULT '0' COMMENT 'Times to deliver',
    `date_to_delay_deliver` datetime DEFAULT NULL COMMENT 'When customes dated to receive packages',
    `period_to_delay_deliver` varchar(50) COLLATE utf8_unicode_ci DEFAULT '' COMMENT 'When customes dated to receive packages',
    `delay_deliver_reason_code` varchar(100) COLLATE utf8_unicode_ci DEFAULT '',
    `reason_id` tinyint (3) unsigned DEFAULT NULL,
    `private_delay_reason_code` varchar(100) COLLATE utf8_unicode_ci DEFAULT '',
    `not_delivered_reason_code` varchar(100) COLLATE utf8_unicode_ci DEFAULT '',
    `tmp_auditing_status` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `tmp_returning_status` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `nth_returned` tinyint (4) unsigned NOT NULL DEFAULT '0',
    `return_message` text COLLATE utf8_unicode_ci,
    `delay_return_reason_code` varchar(100) COLLATE utf8_unicode_ci DEFAULT '',
    `period_to_delay_return` varchar(50) COLLATE utf8_unicode_ci DEFAULT '',
    `date_to_delay_return` datetime DEFAULT NULL,
    `tmp_transfer_to_deliver_status` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `tmp_transfer_to_return_status` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `transfer_return_status` tinyint (3) unsigned NOT NULL DEFAULT '0',
    `transfer_return_at` datetime DEFAULT NULL,
    `accept_transfer_return_at` datetime DEFAULT NULL,
    `extra_type` enum ('normal', 'exchange', 'return') COLLATE utf8_unicode_ci NOT NULL DEFAULT 'normal',
    `parent_id` char(36) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'Parent package id if package type is Exchange or Return',
    `pre_paid_ship` tinyint (4) DEFAULT '0' COMMENT 'Shop must pay when picking',
    `pre_paid_amount` int (10) DEFAULT '0' COMMENT 'money which shop has paid',
    `return_fee` int (10) unsigned NOT NULL DEFAULT '0',
    `rci` smallint (6) DEFAULT NULL COMMENT 'return cost id, gói phí tr? hàng ???c áp d?ng ?? tính ra phí ship',
    `store_fee` int (11) DEFAULT '0' COMMENT 'phgi kho',
    `co_check_no_products` int (10) unsigned NOT NULL DEFAULT '0',
    `co_check_fee` int (10) unsigned NOT NULL DEFAULT '0',
    `transport_type` tinyint (4) DEFAULT '1' COMMENT '1. hàng không, 2. ???ng b?. options are in admin_configs.php',
    `cod_paid` tinyint (3) DEFAULT '0' COMMENT '0: default',
    `tmp_cod_paid` tinyint (3) DEFAULT '0',
    `value` int (11) DEFAULT NULL COMMENT 'Giá tr? th?c',
    `insurance` int (11) DEFAULT NULL COMMENT 'Phí b?o hi?m',
    `sun_deliver` tinyint (1) DEFAULT '0',
    `sun_pick` tinyint (1) DEFAULT '0',
    `cur_station_id` int (11) DEFAULT NULL COMMENT 'kho ?ang ch?a ??n hàng',
    `cur_bag_order` int (11) DEFAULT '0',
    `transport` enum (
      'none',
      'fly',
      'road',
      'truck',
      'railway',
      'waterway'
    ) COLLATE utf8_unicode_ci DEFAULT 'fly',
    `weight` float DEFAULT NULL COMMENT 't?ng cân n?ng c?a ??n hàng',
    `trf_sorting` enum (
      'none',
      'dwait_transfer',
      'rwait_transfer',
      'transferring',
      'done'
    ) COLLATE utf8_unicode_ci DEFAULT 'none',
    PRIMARY KEY (`id`),
    UNIQUE KEY `IDX_ORDER` (`order`),
    KEY `IDX_SHOP_CODE` (`shop_code`),
    KEY `IDX_RETAKE` (
      `deliver_cod_id`,
      `package_status_id`,
      `is_refunded`,
      `is_evicted`,
      `alias`
    ),
    KEY `IDX_SHOP_ID_IS_EXPORTED_IS_CANCEL` (`shop_id`, `is_exported`, `is_cancel`),
    KEY `IDX_TRANSFER_PACKAGES` (
      `transfer_station_id`,
      `transfer_status`,
      `is_cancel`,
      `package_status_id`
    ),
    KEY `IDX_CLIENT_ID` (`client_id`),
    KEY `IDX_TRANSFER_STATUS_ID` (`transfer_return_status`),
    KEY `IDX_DELIVER_COD_ID_PACKAGE_STATUS_ID` (
      `deliver_cod_id`,
      `package_status_id`,
      `is_cancel`
    ),
    KEY `IDX_IS_CANCEL_RETURN_COD_ID_RETURN_STATUS` (`return_cod_id`, `return_status`, `is_cancel`),
    KEY `IDX_PICK_COD_ID_PACKAGE_STATUS_ID` (`pick_cod_id`, `package_status_id`, `is_cancel`),
    KEY `IDX_TRF_SORT` (`trf_sorting`),
    KEY `IDX_CREATED` (`created`, `station_id`),
    KEY `IDX_STATION` (`station_id`, `created`),
    KEY `IDX_PACKAGE_STATUS_ID_IS_CANCEL` (`package_status_id`, `shop_id`, `is_cancel`),
    KEY `IDX_PICK_ORDER` (`pick_cart_id`, `order`),
    KEY `IDX_RETURN_ST` (`return_status`),
    KEY `IDX1` (`pick_tel`, `package_status_id`),
    KEY `IDX2` (`customer_tel`, `package_status_id`),
    KEY `IDX3` (`modified`),
    KEY `IDX4` (`alias`),
    KEY `IDX_CUR_STATION_PKG_STATUS_CREATED` (`cur_station_id`, `package_status_id`, `created`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 3901900007 DEFAULT CHARSET = utf8 COLLATE = utf8_unicode_ci
